config.html, modules/StashGetter.js
From: https://github.com/briansd9/exile-diary/pull/156
=> Get PR from liujordan in

modules/OCRWatcher.js
This fixes Tesseract Interaction
=> fix: Make OCR work again

res/data/constants.json
Add the missing 4 bosses (exarch and eater + smaller bosses) to the right place in the stats.
=> feat: Add the Searing exarch and Eater of worlds

main.js, modules/OCRWatcher.js
- Fix IIR/IIQ order
- Fix overlay being open by default
- Refactor some old code
=> Fix overlay

package.json
Fix repo in `package.json` to have the autoupdater look at the right place
=> fix: Update repo to fix autoupdate

modules/RateGetterV2.js
Remove unused categories from poe.ninja
Because it broke data fetching
=> fix: Remove unused categories

map.html, modules/ItemPricer.js
Fix 6L Pricing in the maps tab
Pricing was split in two, one for the DB, one for the maps tab. I had fixed it in only one place. 
This fixes it on the other.
=> Fix 6l prices

modules/FilterParser.js
Fix filter uploading by adding missing nodes
Refactor some code in there to be a bit cleaner. The code this was pulled from is not really working so we are branching away.
=> Fix filters

modules/MapSearcher.js
=> Fix 6l on stats

modules/ItemCategoryParser.js, modules/MapSearcher.js
Related to #21 , change in this file was missing
=> Missing change for 6l pricing in MapSearcher.js

about.html, res/style.css
Update link for current maintainer, restyle the top part to be more readable on the about page
=> feat: restyle about page

README.md
Update Readme to change links to this fork
=> fix: Change links on readme

config.html, main.js, modules/ClientTxtWatcher.js
Removes Auto Character Switch feature
Because it does not work anymore
=> Fix remove auto switch

modules/RateGetterV2.js, res/maptable.js
Make negative xp/h surface on the main page
Because empty boxes are weird and not useful
=> Feat make negative xp surface

config.html, main.js, modules/RateGetterV2.js
Adds a button in the Debug page to cleanup item rates from poe.ninja and re fetch them
To give users a way to cleanup their data
=> Feat add rates refresh button

modules/RateGetterV2.js, modules/StashGetter.js
Fix ratesReady in ratesGetter
To fix stashes not being refreshed every day
=> Fix stash check

package.json, src/renderer/components/Settings/Settings.css, src/renderer/components/Settings/Settings.tsx, src/renderer/index.js, src/renderer/routes/root.tsx
Add basic Settings Page
To have a frontend for settings for when I plug the backend
Implements #46
=> Feat add settings

src/main/modules/ItemCategoryParser.js
Fix access to constant item
Because I plugged it wrong in the first place
Fixes #66
=> fix: Plug the constant data properly

src/main/modules/OCRWatcher.js, src/main/modules/RunParser.js
Fix OCR Watcher name split
It was not finding images
=> fix: OCR Recognition

src/main/RendererLogger.ts, src/main/index.ts, src/main/modules/RateGetterV2.js, src/renderer/components/LogBox/LogBox.css, src/renderer/components/LogBox/LogBox.tsx, src/renderer/routes/root.tsx, src/renderer/stores/domain/log.ts, src/renderer/stores/logStore.ts
Add log bar at the bottom of the screen
To give insight as to what ED is tracking
=> feat: Add Log

src/main/SettingsManager.ts, src/renderer/components/LogBox/LogBox.tsx
Fix issue that would happen when the app started with no logs
Because it was breaking for some folks
=> fix: Fix map error

src/main/index.ts, src/renderer/components/LogBox/LogBox.tsx
Enable Autoupdater into Alpha channel
To make updates easy for alpha clients
=> Feat readd autoupdater

package-lock.json, package.json, src/renderer/components/LootTable/LootTable.css, src/renderer/components/LootTable/LootTable.tsx, src/renderer/routes/Run.css, src/renderer/routes/Run.tsx, src/renderer/stores/domain/item.ts, src/renderer/stores/itemStore.ts
Add Loot table to the description of a run
To add the missing feature from 0.3
=> Feat add loot table

src/main/modules/ItemPricer.js, src/renderer/routes/Settings.tsx
Add Alternate Splinter Pricing
To make precision of item pricing better
fixes #53
=> Feat add alternate pricing

src/main/index.ts, src/main/modules/RateGetterV2.js, src/renderer/components/Item/Item.tsx, src/renderer/components/LogBox/LogBox.tsx
Fixes RateGetter's settings setup.
To match the new SettingsManager pattern
fixes #73
=> Fix start error

src/main/AuthManager.ts, src/main/GGGAPI.ts, src/main/RatesManager.ts, src/main/SettingsManager.ts, src/main/db/index.ts, src/main/index.ts, src/renderer/index.js, src/renderer/routes/CharacterSelect.css, src/renderer/routes/CharacterSelect.tsx, src/renderer/routes/Login.tsx, src/renderer/routes/LoginBox.tsx, src/renderer/routes/Settings.tsx
- added: new page to login flow to pick your active character
- added: requirement for the Client.txt file location to be set (or you're stuck in that settings page)
- added: proper DB set up on new install / new login / new character
- fixes #107
- fixes #85
- fixes all weird first install issues
=> Fix login flow

package-lock.json, package.json, src/renderer/components/LootTable/LootTable.css, src/renderer/components/LootTable/LootTable.tsx, src/renderer/stores/domain/item.ts, src/renderer/stores/itemStore.ts
- fixed: Item duplicated in run loot table
- fixed: Weird pricing in run loot table
- refactor: Changed the full run loot table (removed data grid, added custom table with sorting and sub-table)
- fixed: Issue with stats -> Run making the page expand infinitely
To fix a ton of issues on loot tables
- fixes #101
=> Fix run breakdown

src/main/StatsManager.ts
- fixed: Shaper Battle breaking the stats page
=> fix: Shaper Battle stats breaking stats page

src/renderer/components/RunEvent/RunEvent.css, src/renderer/components/RunEvent/RunEvent.tsx, src/renderer/components/RunEvent/RunEventIcons.tsx, src/renderer/routes/Run.css
- tracks on the run page:
- shrines
- metamorph
- jun / syndicate encounters
- conquerors
=> Fix run encounters

src/main/GGGAPI.ts, src/main/Responder.ts, src/main/StatsManager.ts, src/main/modules/ScreenshotWatcher.js, src/renderer/components/RunNavigation/RunNavigation.tsx, src/renderer/components/SideNav/SideNav.tsx
- fixed: Sort the run navigation dropdown
- fixed: Make text recognition in image try harder (change the amount of tries it does)
- fixed: Value of Drops not working in stats
- added: Feedback when settings are saved
- fix: Make the API rate limit error less and in a cleaner way
- feat: Make Side Nav show which page you're on
=> Add misc changes

src/main/Responder.ts, src/main/index.ts, src/main/modules/ClientTxtWatcher.js, src/renderer/components/MainSettings/MainSettings.tsx
Add better text and checks for Client.TXT location
To make it clearer that it is needs PoE's client.txt file
=> Feat add more info about clienttxt

src/main/index.ts
Add error message in error title as well as version in body
Adding the app version in the body and the error message in the title makes it easier to navigate issues in github/discord
=> Add error message in error title as well as version in body

src/renderer/index.css, src/renderer/routes/Overlay.css
Fix issue with scrollbars appearing on all pages everywhere, and overlay sometimes growing uncontrollably
Because it's annoying :)
=> Fix scrollbars everywhere

.github/workflows/build.yml
Add build action
To build apps from github actions
=> Feat add build action

src/main/Responder.ts, src/main/index.ts, src/main/modules/ItemCategoryParser.js, src/main/modules/RunParser.js, src/renderer/components/ItemFilterSettings/ItemFilterSettings.css, src/renderer/components/ItemFilterSettings/ItemFilterSettings.tsx, src/renderer/components/MainSettings/MainSettings.tsx, src/renderer/routes/Settings.tsx
Refactor the main process to cleanup window usage
Adds a listener to allow users to restart the app before it gets stuck in that weird "Object is destroyed" mode.
To try and get rid of the Object is destroyed error
=> Refactor the main process to cleanup window usage

src/main/index.ts
Prevent Overlay from being lost on update
To remove pesky Object is destroyed errors
=> Fix object is destroyed on update

src/main/modules/ItemCategoryParser.js
Clean up item categorization
Because seeds were gone from tracking, and some others were never there.
=> Fix seeds not appearing

src/renderer/components/DataSearchForm/DataSearchForm.tsx, src/renderer/routes/Search.tsx
Make the app save search params on search
So that somebody can come back and run the same search again
=> Feat save search params

src/main/db/stats.ts, src/main/index.ts
- Fix logs including full DB Query for search
- Fix formatting for map run in the logs
=> Fix misc search issues

src/main/StatsManager.ts, src/main/modules/RunParser.js
Fix issue where darkshrine dont register right if the run place was not detected properly
Fix their display too
=> Fix darkshrine matching

src/main/db/stats.ts
Fix issue with search never returning runs with no iir/iiq/packsize or map lvl
=> fix: Issue where maps with no iir/iir/packsize/maplvl do not show up in search

src/main/modules/ScreenshotWatcher.ts
Fix Screenshot taking not saving into db
Because the flow was broken
=> fix: Screenshot date formatting to save in db

src/renderer/routes/RunList.tsx
Fix issue with dayjs formatting on the most recent timer
=> fix: DayJS format syntax in Most recent timer

src/renderer/components/Stats/MapStats/MapStats.tsx
Fix issue with alignment of chaos icon in subtables
=> fix: Issue where Chaos were not aligned properly in stats subtables

src/main/modules/InventoryGetter.js
Make inventory getter not fail if checking inventory before full login
fixes #216
=> Make inventory check not fail if searching for it too fast

src/main/Responder.ts, src/main/StatsManager.ts, src/main/db/stats.ts, src/main/index.ts, src/main/modules/ItemPricer.ts, src/main/modules/MapSearcher.js, src/main/modules/StashGetter.ts, src/main/modules/StatsGetter.js, src/renderer/components/Pricing/Price.tsx, src/renderer/components/SideNav/SideNav.css, src/renderer/components/SideNav/SideNav.tsx
Add profit per hour on the Sidenav based on your last runs
fixes #197
=> Feat-add-profit-per-hour

src/main/modules/ItemPricer.ts, src/main/modules/RunParser.js, src/renderer/components/DebugSettings/DebugSettings.tsx
Fix Debugging page timing
Add proper vendor recipe pricing
=> Fix-item-repricing

src/main/StatsManager.ts, src/main/db/stats.ts, src/main/index.ts, src/renderer/components/SideNav/SideNav.tsx, src/renderer/index.css
Add Profit per hour for last 24h and for last hour
To give people a better visibility into their actual profit per hour
=> Add multiple calculated profit per hour

package-lock.json, package.json, src/main/AuthManager.ts
- Remove keytar dependency
- Add locally encrypted electron store instead
Keytar:
- Is no longer maintained
- Saves creds in a not-very secure way (Keys are readable by other programs with no protection on some OS)
- Adds complexity for building
- Does not play well with other OS than Windows
So, it needed to go.
=> Remove keytar

src/main/db/index.ts, src/main/db/rates.ts, src/main/modules/StashGetter.ts
Fix misc errors from end of league move to Standard
Because why not
=> Fix end of league switches

src/main/StashTabsManager.ts, src/main/db/stashtabs.ts
Fix error on startup when no stash is in DB
fixes #251
=> fix: Error when starting the app with no stash in db

src/main/modules/RateGetterV2.ts, src/renderer/components/RunEvent/RunEventIcons.tsx
Fix issue with empty poe.ninja categories messing with pricing
Fix issue with shrine data not matching the pattern the app is looking for (= Run parsing erroring)
=> Feat add affliction pt 2

package-lock.json, package.json, src/main/index.ts, src/renderer/routes/Overlay.css, src/renderer/routes/Overlay.tsx
Make the Overlay moveable
CTRL+F9 triggers a drag and drop UI
For folks who need to move the overlay around for clarity
=> Feat-make-overlay-moveable

src/main/SettingsManager.ts, src/main/index.ts, src/main/modules/StashGetter.ts, src/renderer/components/Pricing/Price.tsx
- Fix weird Price disappearing errors
- Fix Net Worth updates removing your total net worth
- Fix Settings not defaulting properly on first setup
=> Fix-misc-errors

package-lock.json, package.json, src/renderer/components/SideNav/SideNav.tsx, src/renderer/index.css, src/renderer/index.js, src/renderer/routes/Help.css, src/renderer/routes/Help.tsx
Add an Help page in the app
To guide anybody that would not be clear on any feature of the app
=> Feat-add-help-page

src/main/GGGAPI.ts, src/main/StatsManager.ts, src/main/db/stats.ts, src/main/index.ts, src/main/modules/GearChecker.js, src/main/modules/KillTracker.ts, src/main/modules/StashGetter.ts, src/renderer/routes/Overlay.tsx
- feat: Add Wildwood inventory tab
- fix: Stash tab pricing if an item is not recognized
- fix: App errors when the GGG API fails
- feat: Add retry in case the GGG API fails (This is a tentative fix, may evolve in the future)
- fix: Remove a few weird logs
=> Fix-misc-issues

src/helpers/types.ts, src/main/RendererLogger.ts, src/main/StatsManager.ts, src/main/db/index.ts, src/main/db/items.ts, src/main/db/rates.ts, src/main/db/run.ts, src/main/db/stashtabs.ts, src/main/db/stats.ts, src/main/index.ts, src/main/models/Item.ts, src/main/modules/ItemCategoryParser.js, src/main/modules/ItemParser.js, src/main/modules/ItemPricer.ts, src/main/modules/OCRWatcher.js, src/main/modules/RateGetterV2.ts, src/main/modules/RunParser.js, src/main/modules/StashGetter.ts, src/renderer/components/LogBox/LogBox.tsx, src/renderer/components/LootTable/LootTable.tsx, src/renderer/components/Pricing/Pricing.css, src/renderer/routes/Overlay.tsx, src/renderer/stores/domain/item.ts, src/renderer/stores/itemStore.ts, src/renderer/stores/stashTabStore.ts
Change the way values are stored to split original value (when you dropped it) and current value.
This allow to easily reprice everything on the go.
=> Feat-add-original-price

src/main/db/index.ts, src/main/index.ts
- fix: DB migration order
- fix: DB migration location 
To fix issues with the new db field not being setup right
=> Fix db migration

src/helpers/data/items.json, src/main/SettingsManager.ts, src/main/index.ts, src/main/modules/ClientTxtWatcher.js, src/main/modules/ItemCategoryParser.js, src/renderer/routes/CharacterSelect.css, src/renderer/routes/CharacterSelect.tsx, src/renderer/routes/Login.css, src/renderer/routes/LoginBox.tsx
- fixed: colors for login and character selection
- fixed: Category not being set for items not in items.json yet
- fixed: Settings usage in Client Txt Watcher (it did not work well with character switching)
- added: App reload on character change, to fix settings preload
- added: 2 new wand base types
=> Fix Misc errors

src/main/modules/ItemPricer.ts, src/renderer/stores/domain/item.ts, src/renderer/stores/itemStore.ts
- Fix coffin display to separate based on stat and ilvl
- Fix coffin pricing
=> Fix coffins

src/main/modules/ItemPricer.ts
Fix item pricing for :
- Unidentified Uniques
- Maps (including T17)
- Skill Gems
Make Chaos orb be priced at 1c
=> Fix item pricing necropolis

src/helpers/data/items.json
Add a bunch of missing item types
=> Feat add missing types

src/main/SettingsManager.ts, src/renderer/stores/itemStore.ts
Update timers to:
- Save Settings on file
- Save Ignored items on DB
=> Feat improve timers

src/main/db/index.ts
=> feat: Update db to drop gained column

src/main/index.ts, src/main/modules/ItemParser.js
Make Backend save ignores on item add
Fixes #323
=> feat: Update Backend to use ignore helper too

src/main/modules/RateGetterV2.ts
- Remove Allflame Embers
- Remove Coffins
=> fix: Remove Necropolis specific items

src/main/db/index.ts
Change DB Naming pattern to add the league name to it
It prevents folks who use the same name over and over to have an incredibly large db after a few leagues
=> feat: Add league name to db name pattern

src/helpers/item.ts, src/main/db/index.ts, src/main/modules/ItemPricer.ts, src/main/modules/RateGetterV2.ts
Add Kalguuran rune pricing from poe.ninja
=> Feat-add-rune-pricing

package.json, scripts/data-extractor/config.json, src/helpers/data/items.json, src/helpers/item.ts
Add a couple of categories that were not categorized properly:
- Sanctum Relics
- Tinctures
=> Feat-add-uncategorized-items

src/main/index.ts
Make a change of the debug mode switch the log level right away
Because right now you need to restart the app for it to take effect
=> fix: Make debug change live change log lvl

src/helpers/item.ts, src/main/modules/ItemPricer.ts
Add new maps from Settlers
Because not hardcoding it prevents map pricing from working
=> Fix-new-maps

package.json, scripts/start.js, src/helpers/data/items.json, src/main/index.ts, src/main/modules/ClientTxtWatcher.js
Fixes:
- Dev Port used by other tools
- Broken Regex in IP Recognition
Updates: 
- Items table for 3.26
=> Fix misc bugs
