- modules/OCRWatcher.js
Fix old code not matching new one in OCR
Because I suck at 1AM copy/pastes and so I left code calling old vars I deleted.
> fix: Fix issue with OCR cleanup using old names

- main.js
- overlay.html
- package-lock.json
- package.json
Replace `active-win` by `electron-overlay-window` 
`active-win` is troublesome to build today. It has some old dependencies that end up not playing well with modern VSCode/Node-GYP etc...
`electron-overlay-window` does not have this issue, has less dependencies, and only packs the function we actually use for overlays.
Bonus points: Awakened POE Trade uses it too ;)
> Replace active-win by proper overlay lib

- modules/ItemCategoryParser.js
- modules/ItemPricer.js
- res/data/itemCategories.json
- Added Category for each of the memories. (#20)
- Added Categories for Eater of Worlds / Exarch Invitations (#29 )
- Added missing names for Sirius's Map Fragments
note: Cant find out how to get price for these items. currently the invitations are being recognized by the Item pricer but no value is found as shown here:
> Added Memores Categories, Added Missing Sirius's Map Fragments

- main.js
Make the overlay not show pack size if it cannot read it, like in Contracts or blueprints
It's cleaner
Fixes #17
> feat: Prevent unidentified pack size from showing

- modules/ScreenshotWatcher.js
Rewrite the Mods Box Detection
Because the boundary detection made some mods detection not work, and it made it not efficient in general
> Refactor rewrite mod box detection

- main.js
- modules/RateGetterV2.js
- modules/StashGetter.js
Separate RateGetter's Initialization call and Getter
To allow for startup calls to flow properly. When RateGetter is instantiated too early, it tries to read settings before they exists and just die on itself.
This prevented any new install from succeed.
> fix: Separate RateGetter's Init and Getter

- src/main/SettingsManager.ts
Fix issue with db not being initialized when switching to a new character
Because the db was never initialized
Fixes #63
> Fix character switch

- src/main/AuthManager.ts
- src/main/index.ts
- src/main/modules/RateGetterV2.ts
- src/main/modules/StashGetter.ts
- src/renderer/components/StashSettings/StashSettings.tsx
- fixed: Timeouts being too loosely defined
- fixed: Closing down sequence.
These issues made the app stay running even when you thought it closed down properly, which created all of these "object destroyed" errors.
> Fix timeout errors

- src/main/modules/StashGetter.ts
Make the first fullStashInterval check run properly by tying it to the new settings used for the rest of the stash check
I removed the old settings and so it would error in the first check and never really work after that.
> fix: Issue where new users would not have the right settings to trigger the Stash refresh

- old/main.js
- src/main/modules/KillTracker.ts
- src/renderer/components/LogBox/LogBox.tsx
- src/renderer/index.css
- src/renderer/routes/Overlay.tsx
Fix the bug that incubator alert is not working.
Also add the ability for overlay and log to show icons, like here:
(stretching icons a bit with min width 1em, so narrow icons are more noticeable
Also change NodeJS.timer type to be dynamically determined. For some reason on my node 16.17 the type is NodeJS.Timeout and blocking build.
> Fixing a bug in incubator alert

- src/main/modules/StashGetter.ts
Fix StashGetter's settings pull
Because it was failing at picking the league info
> Fix issue with Stashgetter failing to find league info

- src/main/index.ts
Make the app hide the overlay if it ever focuses on PoE but the settings are set to not enable it
To allow for the overlay to just not show for people who prefer that.
This will be done in a better and more clever way in the future, but for now that will do the trick while I go on holidays.
> fix: Enable the option to disable the overlay

- src/main/RendererLogger.ts
- src/main/index.ts
Make overlay initialization run only when ready, and only once
This is fixing an issue where the Overlay was starting too fast and getting disconnected from the main process.
> Fix object is destroyed

- src/main/Responder.ts
- src/main/index.ts
- src/main/modules/ItemCategoryParser.js
- src/main/modules/RunParser.js
- src/renderer/components/ItemFilterSettings/ItemFilterSettings.css
- src/renderer/components/ItemFilterSettings/ItemFilterSettings.tsx
- src/renderer/components/MainSettings/MainSettings.tsx
- src/renderer/routes/Settings.tsx
Move another functionality needed from the old diary -- item filter.
Because the tool kept making me feel richer than I was by counting incubators in.
Haven't thoroughly tested but incubator filter works (ignoring incubator from item filter):
* Before ![Before](https://github.com/Qt-dev/exile-diary/assets/5366284/539c5c05-3d3a-428f-b2e9-013769b1b0e0)
* After ![After](https://github.com/Qt-dev/exile-diary/assets/5366284/b3258046-9cb2-4898-abd3-f2fb17ca9d53)
To test this the debug button is also migrated as `recheckGain` function is already available.
Skip the cached item value and force RunParser to use item pricer every time. It makes the logic more consistent (otherwise for some item it calls pricer while for others doesn't). Tested a bit it seems not affecting other activities than …
> Add item filter, add debug option

- src/main/modules/ScreenshotWatcher.js
Make ScreenshotWatcher abort instead of trying to watch bad folders
Because this was causing a memory/CPU issue.
> fix: Prevent Screenshotwatcher from watching inexistant folder

- src/main/modules/ItemPricer.ts
Prevent undefined filters from making all the stash tab tracking error
To remove the 'ignore' error
> Prevent errors when item filters is not defined yet

- src/renderer/stores/domain/run.ts
Cleanup run store to save deaths
The main page was losing track of death counts
> Cleanup run store to save deaths state

- src/renderer/components/MainSettings/MainSettings.tsx
Fixes the issue where users would get double Client.txt when selecting the Client.txt with the button instead of the folder.
> Cleanup file name in case users select client.txt

- src/main/index.ts
Update channel used in the autoupdater
To prevent users from getting rogue alpha builds without asking
> Update channel to only update from latest

- src/renderer/components/Stats/MainStats/MainStats.tsx
Removed "Unrighteous" stat from the stats page. It does not seem to even just work
> fix: Remove stat that was not showing and not important

- src/main/StatsManager.ts
- src/main/db/stats.ts
Remove league dates from stats pull
It was messing with data in weird cases. There is no point is splitting stats at the moment, we will look into reintroducing it in the future if people need the feature back, but we will need to look into how league dates are defined.
> fix: Remove league dates from stats pull

- src/renderer/routes/Run.tsx
Title
Because it was wrong and displaying IIR instead of Packsize
> Switch Packsize counter to not be IIR

- src/main/Responder.ts
- src/main/index.ts
- src/renderer/components/MainSettings/MainSettings.tsx
- src/renderer/index.css
- src/renderer/routes/Overlay.tsx
- Prevent any click on the overlay
- Make the overlay toggle work with new shortcut (CTRL+F7)
To prevent any weird click issues with Overlays on linux and on windows.
Known Error: The overlay still appears in task bar on windows somehow....
> Feat-remove-overlay-clicks

- src/main/modules/Utils.js
Fix AFK tracking
Because it prevents any stash tab tracking on Linux
> Make AFK tracking more accurate

- src/main/modules/ItemPricer.ts
Fix issue with GetCurrencyByName erroring when no league is set
It was happening at random times and alarming players :)
> fix: Make GetCurrencyByName not error when no league is set

- src/main/db/stashtabs.ts
- src/main/db/stats.ts
Make Stash DB call use `.get` instead of `.all`
To make Stash Tabs show up again in the Stash page. The `.all` changed the format of the db call, and was unnecessary since we were calling for one specific entry (one stash tab data)
> Fix stash not showing

- src/main/SettingsManager.ts
Make Settings setup the default structure on start
To make overlays (and the rest of the app) stop erroring because of silly unset settings
> fix: Make Settings set up default for all needed properties

- src/main/modules/GearChecker.js
Fixes Qt-dev/exile-diary#262
Fixes Qt-dev/exile-diary#264
> Fix tinctures being considered as flasks in `getTempItem`

- src/main/index.ts
Electron has a long standing bug where it does not properly restore the window size on multi monitor setups with different scaling factors:
https://github.com/electron/electron/issues/10862
We work around this by checking if the scaling factors are different and if so, we set the bounds again
> Workaround Electron multi monitor bug

- src/main/models/Item.ts
Fixes https://github.com/Qt-dev/exile-diary/issues/300, https://github.com/Qt-dev/exile-diary/issues/301, https://github.com/Qt-dev/exile-diary/issues/302, https://github.com/Qt-dev/exile-diary/issues/303
I also added better handling for unknown frameTypes in the future, although I'm unsure the implications of polluting the DB with 'Unknown' types. Feel free to only take the first commit if you think the Unknown rarity is problematic.
> Add frameType for Allflames from Necropolis League 

- src/helpers/item.ts
Make the default category not empty 
To ensure not recognized items do not crash the app
> Fix missing category crashes

- src/main/modules/OCRWatcher.js
- src/main/modules/ScreenshotWatcher.ts
Fix some OCR issues:
- Make mods detection work better on thin wide resolutions (yay for Lailloken-UI)
- Make area name detection less prone to error
- Prevent a deadlock state when the text detection was triggered on the area stats and the mods at the same time
> Fix ocr issues

- src/main/SettingsManager.ts
- src/main/db/rates.ts
- src/main/index.ts
- src/main/modules/ItemPricer.ts
- src/main/modules/RateGetterV2.ts
- src/renderer/components/Settings/MainSettings/MainSettings.tsx
Add private league pricing:
- Add new Setting to set an override for pricing (= price everything according to another poe.ninja league)
- Fix issue with new rates not updating old ones
- Cleanup some old code for private leagues that did not work
> Add private league pricing

- package.json
I tested it on three distributions: Nobara (Fedora), Arch, and Debian. On all three, the original build threw a Sharp package error and couldn’t find the libvips library. The issue was in the Linux build process — the libraries weren’t being included.
> fix: missing libvips library for Linux

- src/main/index.ts
- src/renderer/components/Settings/MainSettings/MainSettings.tsx
using IPC request to get around issues when running on windows that leverage nodeIntegration: True. Using the native electron file picker here instead. This fixes issues with path joins too.
> Fix file picker
